# Generated by Django 3.1.4 on 2021-07-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='private_pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('min_time', models.CharField(max_length=20)),
                ('max_time', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '페이지 생성 테이블',
                'db_table': 'private_pages',
            },
        ),
        migrations.CreateModel(
            name='group_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('private_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pages.private_pages')),
            ],
            options={
                'verbose_name': '그룹 멤버 테이블',
                'db_table': 'group_members',
            },
        ),
        migrations.CreateModel(
            name='calendar_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=20)),
                ('private_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='pages.private_pages')),
            ],
            options={
                'verbose_name': '캘린더 일자 테이블',
                'db_table': 'calendar_dates',
            },
        ),
        migrations.CreateModel(
            name='available_times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('calendar_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.calendar_dates')),
                ('group_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to='pages.group_members')),
            ],
            options={
                'verbose_name': '공용 일정표 테이블',
                'db_table': 'available_times',
            },
        ),
    ]
