# Generated by Django 3.1.4 on 2021-06-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=False, max_length=20)),
                ('month', models.CharField(default=False, max_length=20)),
                ('day', models.CharField(default=False, max_length=20)),
                ('day_of_week', models.CharField(default=False, max_length=20)),
            ],
            options={
                'verbose_name': '캘린더 일자 테이블',
                'db_table': 'calendar_dates',
            },
        ),
        migrations.CreateModel(
            name='private_pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=False, max_length=20)),
                ('title', models.CharField(default=False, max_length=20)),
                ('min_time', models.CharField(default=False, max_length=20)),
                ('max_time', models.CharField(default=False, max_length=20)),
                ('calendar_date_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_page.calendar_dates')),
            ],
            options={
                'verbose_name': '페이지 생성 테이블',
                'db_table': 'private_pages',
            },
        ),
        migrations.CreateModel(
            name='group_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=False, max_length=20)),
                ('user_pw', models.CharField(default=False, max_length=20)),
                ('private_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt_page.private_pages')),
            ],
            options={
                'verbose_name': '로그인 테스트 테이블',
                'db_table': 'group_members',
            },
        ),
    ]
